---
version: '3.6'

services:
  adminer:
    depends_on:
    - db
    image: adminer
    ports:
    - 8091:8080/tcp

  db:
    environment:
    - MYSQL_DATABASE=nca_sulu
    - MYSQL_PASSWORD=nca_sulu
    - MYSQL_ROOT_PASSWORD=aex5iejaeTh3ongo4chu
    - MYSQL_USER=nca_sulu
    - TZ=Europe/Berlin
    image: mariadb
    ports:
    - 3306:3306/tcp
    volumes:
    - './db-live:/var/lib/mysql'
    - './db-init:/docker-entrypoint-initdb.d'
    restart: always

  web:
    build:
      context: .
      target: webserver
    depends_on:
    - db
    environment:
    - DATABASE_URL=mysql://nca_sulu:nca_sulu@db:3306/nca_sulu
    - MAIL_URL=null://localhost
    - SULU_ADMIN_EMAIL=
    volumes:
      - './:/var/www/html'
    ports:
    - 8090:80/tcp
    restart: always
