---
version: '2'

services:
  db:
    environment:
    - MYSQL_DATABASE_FILE=/run/secrets/sulu_nca_database_name
    - MYSQL_PASSWORD_FILE=/run/secrets/sulu_nca_database_pass
    - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/sulu_nca_database_root_pass
    - MYSQL_USER_FILE=/run/secrets/sulu_nca_database_user
    image: mariadb
    labels:
      io.rancher.container.pull_image: always
    restart: always
    secrets:
    - sulu_nca_database_name
    - sulu_nca_database_pass
    - sulu_nca_database_root_pass
    - sulu_nca_database_user
    volumes:
    - sulu_db_data:/var/lib/mysql
    - sulu_db_transfer:/docker-entrypoint-initdb.d

  web:
    depends_on:
    - db
    environment:
    - APP_ENV_FILE=/run/secrets/sulu_nca_app_env
    - APP_SECRET_FILE=/run/secrets/sulu_nca_app_secret
    - DATABASE_URL_FILE=/run/secrets/sulu_nca_database_url
    - DATABASE_HOST_FILE=/run/secrets/sulu_nca_database_host
    - DATABASE_NAME_FILE=/run/secrets/sulu_nca_database_name
    - DATABASE_PASS_FILE=/run/secrets/sulu_nca_database_pass
    - DATABASE_USER_FILE=/run/secrets/sulu_nca_database_user
    - MAIL_URL_FILE=/run/secrets/sulu_nca_mail_url
    - SULU_ADMIN_EMAIL_FILE=/run/secrets/sulu_admin_email
    - GOOGLE_API_KEY_FILE=/run/secrets/sulu_GOOGLE_API_KEY
    - TWITTER_API_KEY_FILE=/run/secrets/sulu_nca_twitter_api_key
    - TWITTER_API_SECRET=/run/secrets/sulu_nca_twitter_api_secret
    - TWITTER_ACCESS_TOKEN_FILE=/run/secrets/sulu_nca_twitter_access_token
    - TWITTER_ACCESS_SECRET=/run/secrets/sulu_nca_twitter_access_secret
    image: $WEB_IMAGE
    labels:
      traefik.docker.network: proxy
      traefik.enable: true
      traefik.frontend.passHostHeader: true
      traefik.frontend.rule: 'Host:$HTTP_URL'
      traefik.frontend.entryPoints: http,https
      traefik.port: 80
      traefik.frontend.headers.SSLRedirect: true
    restart: always
    secrets:
    - sulu_nca_app_env
    - sulu_nca_app_secret
    - sulu_nca_database_url
    - sulu_nca_database_host
    - sulu_nca_database_name
    - sulu_nca_database_pass
    - sulu_nca_database_user
    - sulu_nca_mail_url
    - sulu_admin_email
    - sulu_GOOGLE_API_KEY
    - sulu_nca_twitter_api_key
    - sulu_nca_twitter_api_secret
    - sulu_nca_twitter_access_token
    - sulu_nca_twitter_access_secret
    volumes:
    - sulu_web_uploads:/var/www/html/uploads
    - sulu_web_var:/var/www/html/var
    - sulu_web_transfer:/var/www/transfer

volumes:
  sulu_db_data:
    driver: local
  sulu_web_uploads:
    driver: local
  sulu_web_var:
    driver: local
  sulu_web_transfer:
    driver: local
    external: true
  sulu_db_transfer:
    driver: local
    external: true

secrets:
  sulu_nca_database_name:
    external: true
  sulu_nca_database_pass:
    external: true
  sulu_nca_database_root_pass:
    external: true
  sulu_nca_database_user:
    external: true
  sulu_nca_database_host:
    external: true
  sulu_nca_app_env:
    external: true
  sulu_nca_app_secret:
    external: true
  sulu_nca_database_url:
    external: true
  sulu_nca_mail_url:
    external: true
  sulu_admin_email:
    external: true
  sulu_nca_twitter_api_key:
    external: true
  sulu_nca_twitter_api_secret:
    external: true
  sulu_nca_twitter_access_token:
    external: true
  sulu_nca_twitter_access_secret:
    external: true
  GOOGLE_API_KEY:
    external: true
